id: I606EBA1E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:48:36+00:00'
last_modified: '2022-06-08T08:22:42.823001+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD20781
  title: དབྱར་གནས་འདོན་ཆ་དང་སྨོན་ལམ་སྐོར་སྣ་ཚོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    37C0:
      image_group_id: I2PD20829
      title: ''
      total_pages: 554
      order: 1
      base_file: 37C0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
